routing.datasource.session-data-source-bean-name = uisamples_SessionDataSource
routing.datasource.url-prefix = jdbc:hsqldb:mem:
routing.datasource.default-session-id = default_Id

session.datasource.driver-class-name = org.hsqldb.jdbc.JDBCDriver
session.datasource.username = sa
session.datasource.password =
session.datasource.maxTotal = 5

jmix.data.dbms-type = HSQL

main.liquibase.change-log = io/jmix/uisamples/liquibase/changelog.xml

server.servlet.context-path=/ui-samples
server.servlet.session.timeout = 10m

vaadin.heartbeatInterval = 180

jmix.ui.main-view-id = MainView
jmix.uisamples.menu-config = /io/jmix/uisamples/menu/uisamples-menu.xml
jmix.ui.composite-menu = true
jmix.ui.view.use-save-confirmation=false
jmix.ui.component.checkbox-required-state-initialization-enabled=false

jmix.core.available-locales = en,ru

spring.ai.model.chat = none

# Launch the default browser when starting the application in development mode
vaadin.launch-browser = false

logging.level.org.atmosphere = warn

# 'debug' level logs SQL generated by EclipseLink ORM
logging.level.eclipselink.logging.sql = info

# 'debug' level logs data store operations
logging.level.liquibase = warn
logging.level.io.jmix.core.datastore = info
logging.level.io.jmix.uisamples.bean.UiSamplesRoutingDataSource = debug
logging.level.io.jmix.uisamples.view.sys.sampleview.SampleView = debug

# 'debug' level logs all Jmix debug output
logging.level.io.jmix = info